# Generated by Django 2.1.5 on 2019-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=30)),
                ('base_health', models.IntegerField()),
                ('base_magic_res', models.IntegerField()),
                ('base_mana', models.IntegerField()),
                ('base_spell_dmg', models.IntegerField()),
                ('base_armor', models.IntegerField()),
                ('base_att_persec', models.IntegerField()),
                ('base_damage', models.IntegerField()),
                ('base_movement_speed', models.IntegerField()),
            ],
        ),
    ]
