# Generated by Django 2.1.5 on 2019-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190722_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_thumbnail',
            field=models.ImageField(default='hero_thumbnails/Juggernaut_icon.png', upload_to='hero_thumbnails'),
        ),
    ]
