# Generated by Django 2.1.5 on 2019-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190724_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='base_armor',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_att_persec',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_damage',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_health',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_magic_res',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_mana',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_movement_speed',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='base_spell_dmg',
            field=models.IntegerField(default=25),
        ),
    ]
