# Generated by Django 2.1.5 on 2019-07-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190728_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroUniqueSlug',
            fields=[
                ('hero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Hero')),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
            
        ),
    ]
