# Generated by Django 2.1.5 on 2019-07-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190729_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='slug',
        ),
    ]
