# Generated by Django 2.1.5 on 2019-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_hero_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='base_armor',
            new_name='hero_base_armor',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_att_persec',
            new_name='hero_base_att_persec',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_damage',
            new_name='hero_base_damage',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_health',
            new_name='hero_base_health',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_magic_res',
            new_name='hero_base_magic_res',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_mana',
            new_name='hero_base_mana',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_movement_speed',
            new_name='hero_base_movement_speed',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='base_spell_dmg',
            new_name='hero_base_spell_dmg',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_lore',
            field=models.TextField(default='Default hero lore'),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_main_attribute',
            field=models.CharField(choices=[('STRENGTH', 'Strength'), ('AGILITY', 'Agility'), ('INTELLIGENCE', 'Intelligence')], default='STR', max_length=12),
        ),
    ]
