# Generated by Django 2.2.3 on 2019-07-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190729_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['hero_name']},
        ),
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=20),
        ),
    ]
