# Generated by Django 2.2.3 on 2019-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190729_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
