# Generated by Django 2.2.3 on 2019-07-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190729_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_attribute_image',
            field=models.ImageField(default='Strength_attribute_symbol.png', upload_to='hero_thumbnails'),
        ),
    ]
