# Generated by Django 2.2.3 on 2019-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_hero_hero_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_counters',
            field=models.ManyToManyField(blank=True, to='mainapp.Hero'),
        ),
    ]
