# Generated by Django 2.2.3 on 2019-08-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190731_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_counters',
        ),
    ]
