# Generated by Django 2.2.3 on 2019-08-04 01:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190803_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARRY', 'Item title 1.1'), ('SUPPORT', 'Item title 1.2'), ('NUKER', 'Item title 1.3'), ('DISABLER', 'Item title 1.4'), ('JUNGLER', 'Item title 1.5'), ('DURABLE', 'Item title 1.4'), ('ESCAPE', 'Item title 1.4'), ('PUSHER', 'Item title 1.4'), ('INITIATOR', 'Item title 1.4'), ('ROAMER', 'Item title 1.4'), ('RANGED', 'Item title 1.4'), ('MELEE', 'Item title 1.4')], max_length=88),
        ),
    ]
