# Generated by Django 2.2.3 on 2019-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_item_item_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_stats',
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat1',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat10',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat2',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat3',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat4',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat5',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat6',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat7',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat8',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stat9',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
